root: true
extends:
  - remcohaszing
  - remcohaszing/typechecking
rules:
  no-duplicate-imports: off

  import/no-extraneous-dependencies: off

  jsdoc/require-jsdoc: off
overrides:
  - files:
      - examples/esbuild-demo/build.js
    rules:
      no-console: off
